[package]
name = "test-crate-9191"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A short description of my package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"